services:
  backend:
    build:
      context: .
      target: server-run
      dockerfile: Dockerfile.dev
    ports:
      - "3000-3010:3000"
    restart: unless-stopped
    networks:
      - load_balancer_network

  load_balancer:
    container_name: load_balancer
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: balancer-run
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - load_balancer_network
    depends_on:
      - backend
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  load_balancer_network:
    driver: bridge
